version: '3'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: app
    volumes:
      - .:/var/www/html
    depends_on:
      - db
    environment:
      - DB_HOST=db
      - DB_NAME=bank
      - DB_USER=user
      - DB_PASS=pass

  db:
    image: postgres:14
    container_name: db
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=banking
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=banking_password
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./migrations/dump.sql:/docker-entrypoint-initdb.d/dump.sql  # Добавлено

  web:
    image: nginx:alpine
    container_name: web
    ports:
      - "8080:80"
    volumes:
      - .:/var/www/html
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app

volumes:
  db_data: